version: '3.9'

services:
  postgres-db:
    image: postgres:16.2
    environment:
        POSTGRES_PASSWORD: P@ssw0rd
        POSTGRES_USER: postgres
        POSTGRES_DB: planets_star_wars_api
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - api-network

  app:
    build: ./
    ports:
      - "8080:8080"
    expose:
      - 8080
    depends_on:
      - postgres-db
    command: mvn spring-boot:run
    restart: always
    environment:
      SPRING.DATASOURCE.URL: jdbc:postgresql://postgres-db:5432/planets_star_wars_api
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: P@ssw0rd
    networks:
      - api-network


networks:
  api-network: {}